config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'


  resources :attachments, only: :destroy

  resources :questions do
    resources :answers, shallow: true, only: %i[create update destroy] do
      patch 'best', on: :member
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  has_many_attached :files

  belongs_to :question
  belongs_to :author, class_name: 'User'

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def user?(user)
    author == user
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  has_many_attached :files

  belongs_to :author, class_name: 'User'
  belongs_to :best_answer, class_name: 'Answer', optional: true

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, foreign_key: :author_id, dependent: :destroy
  has_many :answers, foreign_key: :author_id, dependent: :destroy

  validates :last_name, :first_name, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :find_answer, only: %i[destroy update best]
  before_action :authenticate_user!

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params.merge(author: current_user ))
    if @answer.persisted?
      flash[:notice] = 'Answer created successfully'
    end
  end

  def update
    if @answer.user?(current_user)
      @answer.update(answer_params)
      flash[:notice] = 'Answer edited successfully'
    end
  end

  def destroy
    if @answer.author == current_user
      @answer.destroy
      flash[:notice] = 'Your reply has been successfully deleted'
    else
      flash[:alert] = "You cannot delete someone else's answer"
    end
  end

  def best
    question = @answer.question
    question.update(best_answer: @answer)
    @best_answer = question.best_answer
    @answers = question.answers.where.not(id: @best_answer.id)

    flash[:notice] = 'Best answer selected successfully'
  end

  private

  def answer_params
    params.require(:answer).permit(:body, files: [])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!

  def destroy
    @attachment = ActiveStorage::Attachment.find(params[:id])
    @attachment.purge
    flash[:notice] = 'File deleted successfully'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show ]

  before_action :find_question, only: %i[show destroy update]

  def index
    @questions = Question.all
  end

  def show
    @answers = @question.answers.where.not(id: @question.best_answer)
  end

  def new
    @question = current_user.questions.new
  end

  def update
    if @question.user?(current_user)
      @question.update(question_params)
      flash[:notice] = 'Your question has been successfully edited.'
    end
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to questions_path, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def destroy
    if @question.user?(current_user)
      @question.destroy
      redirect_to questions_path, notice: 'Your question has been successfully deleted'
    else
      redirect_to questions_path, alert: "You can't delete someone else's question"
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, files: [])
  end

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message_css_class(key)
    case key.to_sym
    when :notice then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error then 'alert alert-error'
    when :alert then 'alert alert-danger'
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
.answer_error(data-answer-id=answer.id)
.answer(data-answer-id=answer.id)
  br
  br
    li = answer.body

    = render 'shared/attachment', resource: answer

    -if answer.user?(current_user)
      = link_to 'Best', best_answer_path(answer),method: :patch,remote: true
      || |
      = link_to "Delete", answer_path(answer),
                              method: :delete,
                              remote: true,
                              data: {confirm: 'Are you sure?'}
      || |
      = link_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: answer.id }


      = render 'answers/edit_form', answer: answer

app/views/answers/_best_answer.html.slim
.(data-answer-id=best_answer.id)
  h3 Best answer:
  li = best_answer.body
  = render 'shared/attachment', resource: best_answer
  -if best_answer.user?(current_user)
    = link_to "Delete", answer_path(best_answer),
                            method: :delete,
                            remote: true,
                            data: {confirm: 'Are you sure'}
    || |
    = link_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: best_answer.id }

    = render 'answers/edit_form', answer: best_answer

app/views/answers/_edit_form.html.slim
= form_with model: answer, local: false, class: 'hidden', id: "edit-answer-#{answer.id}" do |form|
  p
    = form.label :body
    br
    = form.text_area :body, size: "70x10"
  p
    = form.label :files
    br
    = form.file_field :files, multiple: true
  p
    = form.submit class: 'save-answer', data: { answer_id: answer.id }

app/views/answers/_form.html.slim
= form_with model: [@question, answer], local: false, class: 'new-answer' do |form|
  p
    = form.label :body
    br
    = form.text_area :body, size: "70x10"
  p
    = form.label :files
    br
    = form.file_field :files, multiple: true, direct_upload: true
  p
    = form.submit

app/views/answers/best.js.erb
$('.flash_message').html('<%= render 'shared/flash'%>');

<% if @best_answer.present?%>
  $('.best_answer').html('<%= j render  'answers/best_answer', best_answer: @best_answer%>')
  $('.answers').html('<%= j render  @answers%>')
<% end%>

app/views/answers/create.js.erb
$('.flash_message').html('<%= render 'shared/flash'%>');
$('.answer_errors').html('<%= render 'shared/errors', resource: @answer%>')

<% if @answer.persisted?%>
  $('.answers').append('<%= j render @answer%>')
  $('form.new-answer #answer_body').val('')
  $('form.new-answer #answer_files').val('')
<% end%>

app/views/answers/destroy.js.erb
$('.flash_message').html('<%= render 'shared/flash' %>');

<% if @answer.destroyed? %>
  $('[data-answer-id="<%= @answer.id %>"]').remove();
<% end %>

app/views/answers/update.js.erb
$('.flash_message').html('<%= render 'shared/flash' %>');
$('.answer_error[data-answer-id="<%= @answer.id %>"]').html('<%= render 'shared/errors', resource: @answer%>');


<% if !@answer.errors.present? %>
  <% if @answer.question.best_answer == @answer %>
    $('.best_answer').html('<%= j render  'answers/best_answer', best_answer: @answer%>')
  <% else %>
    $('.answer[data-answer-id="<%= @answer.id %>"]').replaceWith('<%= j render @answer %>');
  <% end %>
<% end %>

app/views/attachments/destroy.js.erb
<% if @attachment.destroyed? %>
  $('.flash_message').html('<%= render 'shared/flash' %>');
  $('.file[data-file-id="<%= @attachment.id %>"]').remove()
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav'%>
    <%= render 'shared/flash'%>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, class: 'form-question', local: false do |form|
  p
    = form.label :title
    br
    = form.text_field :title
  p
    = form.label :body
    br
    = form.text_area :body, size: '70x10'
  p
    p
    = form.label :files
    br
    = form.file_field :files, multiple: true, direct_upload: true
  p
    = form.submit class: 'save-question'

app/views/questions/_question.html.slim
- @questions.each do |question|
  h2 = link_to question.title, question

  p = question.body
  -if question.user?(current_user)
    = link_to 'Delete', question_path(question),
                        method: :delete,
                        data: {confirm: 'Are you sure?'}

app/views/questions/index.html.slim
h2 = 'Questions'

h3 = link_to 'Ask question', new_question_path

= render 'question'

app/views/questions/new.html.slim
= render 'form'
p = link_to 'Home', root_path

app/views/questions/show.html.slim
.question_show
  .flash_message

  h2 id="question-title" =  "Question title: #{@question.title}"
  p id="question-body"  = @question.body

  .files
    = render 'shared/attachment', resource: @question

  -if @question.user?(current_user)
    = link_to "Edit", '#', class: 'edit-question-link'

    .question_errors
    = render 'form'
br
.answers_all
  .best_answer
    -if @question.best_answer.present?
      = render 'answers/best_answer', best_answer: @question.best_answer
  .answers
    = render @answers

.answer_errors
= render 'answers/form', answer: @question.answers.new

p = link_to 'Home', root_path

app/views/questions/update.js.erb
$('.flash_message').html('<%= render 'shared/flash' %>');
$('.question_errors').html('<%= render 'shared/errors', resource: @question %>');
$('#question-title').html('<%= j "Question title: #{@question.title}" %>');
$('#question-body').html('<%= j @question.body %>');
$('.files').replaceWith('<%= j render 'shared/attachment', resource: @question%>');

app/views/shared/_attachment.html.slim
-if resource.files.attached?
  - resource.files.each do |file|
    .file(data-file-id=file.id)
      p = link_to file.filename.to_s, url_for(file)
      -if resource.user?(current_user)
        p = link_to "Delete attach", attachment_path(file), method: :delete, remote: true,
                                                                data: {confirm: 'Are you sure?'}

app/views/shared/_errors.html.slim
-if resource.present? && resource.errors.present?
  div
    h2 = "#{pluralize(resource.errors.count, 'error')} detected"

    = resource.errors.full_messages.each do |message|
      li = message

app/views/shared/_flash.html.slim
-flash.each do |key, message|
  = content_tag :p, message.html_safe, class: flash_message_css_class(key)

app/views/shared/_nav.html.slim
.right-button
  -if user_signed_in?
    = button_to "Sign out", destroy_user_session_path, method: :delete
  -else
    = button_to "Sign in", new_user_session_path